---
- name: Import custom fault injection tasks
  ansible.builtin.import_tasks:
    file: inject_custom.yaml
  when:
    - fault.custom is defined

- name: Import Chaos Mesh fault injection tasks
  ansible.builtin.import_tasks:
    file: inject_chaos_mesh.yaml
  vars:
    spec: "{{ fault.chaos_mesh }}"
  when:
    - fault.chaos_mesh is defined

- name: Import Otel Demo fault injection tasks
  ansible.builtin.import_tasks:
    file: inject_otel_demo.yaml
  when:
    - fault.otel_demo is defined

- name: Import Valkey fault injection tasks
  ansible.builtin.import_tasks:
    file: inject_valkey.yaml
  when:
    - fault.valkey is defined

# - name: Import misconfigured service mesh fault injection tasks (sidecar injection off)
#   ansible.builtin.include_tasks:
#     file: inject_custom_sidecar_injection_off.yaml
#   vars:
#     spec: "{{ fault.misconfigured_service_mesh.sidecar_injection_off }}"
#   when:
#     - fault.type == 'misconfigured_service_mesh'
#     - fault.misconfigured_service_mesh.misconfiguration_type == 'sidecar_injection_off'

# - name: Import misconfigured service mesh fault injection tasks (authorization policy deny)
#   ansible.builtin.include_tasks:
#     file: inject_custom_authorization_policy_deny.yaml
#   vars:
#     spec: "{{ fault.misconfigured_service_mesh.authorization_policy_deny }}"
#   when:
#     - fault.type == 'misconfigured_service_mesh'
#     - fault.misconfigured_service_mesh.misconfiguration_type == 'authorization_policy_deny'
