---
tools_instances:
  clickhouse:
    name: clickhouse
    namespace: clickhouse
  opentelemetry_collectors:
    names:
      jaeger: jaeger
      kubernetes_events: kubernetes-events
      kubernetes_objects_snapshot: kubernetes-objects-snapshot
    namespace: opentelemetry-collectors
