---
- name: Create the release namespace for Clickhouse Operator
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ tools_helm_releases.clickhouse_operator.namespace }}"
        labels:
          it-bench/gateway: "true"
          it-bench/monitoring: "true"
    state: present

- name: Install Clickhouse Operator
  kubernetes.core.helm:
    chart_ref: altinity-clickhouse-operator
    chart_repo_url: https://docs.altinity.com/clickhouse-operator/
    chart_version: 0.25.5
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ tools_helm_releases.clickhouse_operator.name }}"
    release_namespace: "{{ tools_helm_releases.clickhouse_operator.namespace }}"
    release_state: present
    timeout: 10m0s
    values:
      configs:
        files:
          config.yaml:
            watch:
              namespaces:
                - "{{ tools_instances.clickhouse.namespace }}"
      podAnnotations:
        openshift.io/required-scc: restricted-v2
      serviceMonitor:
        enabled: "{{ tools_required.prometheus }}"
    wait: true

- name: Create the release namespace for Clickhouse
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ tools_instances.clickhouse.namespace }}"
        annotations:
          openshift.io/sa.scc.mcs: s0:c30,c10
          openshift.io/sa.scc.uid-range: 100/100
          openshift.io/sa.scc.supplemental-groups: 101/100
        labels:
          it-bench/monitoring: "true"
    state: present

- name: Create Clickhouse Kubernetes objects
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    namespace: "{{ tools_instances.clickhouse.namespace }}"
    state: present
    src: files/clickhouse/{{ item }}
  loop:
    - secret.yaml
    - templates.yaml
    - installation.yaml

- name: Fetch all Clickhouse Installations
  kubernetes.core.k8s_info:
    api_version: clickhouse.altinity.com/v1
    kind: ClickHouseInstallation
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    namespace: "{{ tools_instances.clickhouse.namespace }}"
  register: tools_clickhouse_installations_info

- name: Wait for all Clickhouse Installations to reach ready state
  kubernetes.core.k8s_info:
    api_version: "{{ resource.apiVersion }}"
    kind: "{{ resource.kind }}"
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    name: "{{ resource.metadata.name }}"
    namespace: "{{ resource.metadata.namespace }}"
    wait: true
  loop: "{{ tools_clickhouse_installations_info.resources }}"
  loop_control:
    label: clickhouseinstallation/{{ resource.metadata.name }}
    loop_var: resource
  register: tools_clickhouse_installation_info
  until:
    - tools_clickhouse_installation_info.resources[0].status is defined
    - tools_clickhouse_installation_info.resources[0].status.status is defined
    - tools_clickhouse_installation_info.resources[0].status.status == 'Completed'
  retries: 10
  delay: 30

- name: Append networking information to list
  ansible.builtin.set_fact:
    tools_gateway_http_routes: "{{ tools_gateway_http_routes + [http_route] }}"
  vars:
    http_route:
      name: "{{ tools_instances.clickhouse.name }}"
      namespace: "{{ tools_instances.clickhouse.namespace }}"
      path: /clickhouse
      service:
        name: "{{ tools_helm_releases.clickhouse.name }}-clickhouse"
        port: 8123
      ui_path: /clickhouse/play

- name: Create OpenShift Routes
  when:
    - tools_cluster.platform == "openshift"
  block:
    - name: Create list of routes for Clickhouse Installations
      ansible.builtin.set_fact:
        tools_clickhouse_routes: |
          {{
            (
              tools_clickhouse_routes | default([])
            ) +
            [
              {
                'name': resource.metadata.name,
                'namespace': resource.metadata.namespace,
                'service': tools_helm_releases.clickhouse.name + '-clickhouse',
                'target_port': 'http'
              }
            ]
          }}
      loop: "{{ tools_clickhouse_installations_info.resources }}"
      loop_control:
        label: clickhouseinstallation/{{ resource.metadata.name }}
        loop_var: resource

    - name: Create Route for Clickhouse UI
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        template: templates/networking/openshift/route.j2
        state: present
      loop: "{{ tools_clickhouse_routes }}"
      loop_control:
        label: route/{{ route.name }}
        loop_var: route
