---
- name: Install NGINX Fabric Gateway on Kubernetes
  when:
    - tools_cluster.platform == "kubernetes"
  block:
    - name: Add Kubernetes Gateway API CRDs
      kubernetes.core.k8s:
        apply: true
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        server_side_apply:
          field_manager: kubectl-client-side-apply
        src: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml

    - name: Create release namespace for NGINX Fabric Gateway
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        state: present
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ tools_helm_releases.nginx_fabric_gateway.namespace }}"
            labels:
              it-bench/monitoring: "true"

    - name: Install NGINX Fabric Gateway
      kubernetes.core.helm:
        chart_ref: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
        chart_version: 2.2.1
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        release_name: "{{ tools_helm_releases.nginx_fabric_gateway.name }}"
        release_namespace: "{{ tools_helm_releases.nginx_fabric_gateway.namespace }}"
        release_state: present
        values: "{{ lookup('ansible.builtin.template', 'templates/helm_values/nginx_fabric_gateway.j2') | from_yaml }}"
        wait: true

    - name: Create Gateway
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        template: templates/networking/kubernetes/gateway.j2
        state: present

    - name: Create HTTPRoute
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        template: templates/networking/kubernetes/httproute.j2
        state: present
      loop: "{{ tools_gateway_http_routes }}"
      loop_control:
        label: httproute/{{ route.name }}
        loop_var: route

- name: Create Routes for Observability Stack
  when:
    - tools_cluster.platform == "openshift"
  block:
    - name: Create Route objects for Observability Stack
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        template: templates/networking/openshift/route.j2
        state: present
      loop: "{{ tools_openshift_routes }}"
      loop_control:
        label: route/{{ route.name }}
        loop_var: route
