---
- name: Install Prometheus Kubernetes Stack
  when:
    - tools_cluster.platform == "kubernetes"
  block:
    - name: Create the release namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ tools_helm_releases.prometheus.namespace }}"
            labels:
              it-bench/gateway: "true"
              it-bench/monitoring: "true"
        state: present

    - name: Install Prometheus Operator and Prometheus
      kubernetes.core.helm:
        chart_ref: kube-prometheus-stack
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        chart_version: 79.4.1
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        release_name: "{{ tools_helm_releases.prometheus.name }}"
        release_namespace: "{{ tools_helm_releases.prometheus.namespace }}"
        release_state: present
        timeout: 10m0s
        values:
          alertmanager:
            enabled: false
          defaultRules:
            rules:
              alertmanager: false
          grafana:
            enabled: false
          kubeEtcd:
            enabled: "{{ tools_cluster.provider == 'kind' }}"
          kubeProxy:
            enabled: "{{ tools_cluster.provider == 'kind' }}"
          prometheus:
            prometheusSpec:
              additionalArgs:
                - name: web.enable-otlp-receiver
                  value: ""
              podMonitorNamespaceSelector:
                matchLabels:
                  it-bench/monitoring: "true"
              podMonitorSelectorNilUsesHelmValues: false
              ruleNamespaceSelector:
                matchLabels:
                  it-bench/monitoring: "true"
              ruleSelectorNilUsesHelmValues: false
              serviceMonitorNamespaceSelector:
                matchLabels:
                  it-bench/monitoring: "true"
              serviceMonitorSelectorNilUsesHelmValues: false
        wait: true

    - name: Append networking information to list
      ansible.builtin.set_fact:
        tools_gateway_http_routes: "{{ tools_gateway_http_routes + [http_route] }}"
      vars:
        http_route:
          name: "{{ tools_helm_releases.prometheus.name }}"
          namespace: "{{ tools_helm_releases.prometheus.namespace }}"
          path: /prometheus
          service:
            name: "{{ tools_helm_releases.prometheus.name }}-kube-prometheus-prometheus"
            port: 9090

- name: Install OpenShift Prometheus Stack
  when:
    - tools_cluster.platform == "openshift"
  block:
    - name: Enable OpenShift user workload monitoring
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        state: present
        src: files/openshift/user-workload-monitoring-config.yaml

    - name: Wait for Prometheus workload pods to start
      kubernetes.core.k8s_info:
        kind: Pod
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        label_selectors:
          - app.kubernetes.io/component = prometheus
          - app.kubernetes.io/instance = user-workload
        namespace: openshift-user-workload-monitoring
        wait: true
        wait_condition:
          type: Ready
          status: "True"
        wait_timeout: 300
