---
- name: Delete Clickhouse Kubernetes objects
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    namespace: "{{ tools_instances.clickhouse.namespace }}"
    state: absent
    src: files/clickhouse/{{ item }}
    wait: true
  loop:
    - installation.yaml
    - templates.yaml
    - secret.yaml

- name: Delete the instance namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ tools_instances.clickhouse.namespace }}"
    state: absent
    wait: true

- name: Uninstall Clickhouse Operator
  kubernetes.core.helm:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ tools_helm_releases.clickhouse_operator.name }}"
    release_namespace: "{{ tools_helm_releases.clickhouse_operator.namespace }}"
    release_state: absent
    wait: true

- name: Delete the release namespaces
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ tools_helm_releases.clickhouse_operator.namespace }}"
    state: absent
    wait: true

- name: Append Alinity ClickHouse related CRDs to list
  ansible.builtin.set_fact:
    tools_custom_resource_definitions: "{{ tools_custom_resource_definitions + crds }}"
  vars:
    crds: |
      {{
        tools_crd_info.resources |
        community.general.json_query("[?ends_with(spec.group, 'altinity.com')]")
      }}
