---
- name: Uninstall NGINX Fabric Gateway
  kubernetes.core.helm:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ tools_helm_releases.nginx_fabric_gateway.name }}"
    release_namespace: "{{ tools_helm_releases.nginx_fabric_gateway.namespace }}"
    release_state: absent
    wait: true

- name: Delete the release namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ tools_helm_releases.nginx_fabric_gateway.namespace }}"
    state: absent
    wait: true

- name: Retrieve all CRDs
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
  register: tools_crd_info

- name: Remove Kubernetes Gateway API CRDs
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: "{{ crd.apiVersion }}"
      kind: "{{ crd.kind }}"
      metadata:
        name: "{{ crd.metadata.name }}"
    state: absent
    wait: true
  loop: |
    {{
      tools_crd_info.resources |
      community.general.json_query("[?spec.group=='gateway.networking.k8s.io']")
    }}
  loop_control:
    label: customresourcedefinition/{{ crd.metadata.name }}
    loop_var: crd
