---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-init-prometheus
  labels:
    app.kubernetes.io/name: clickhouse
data:
  01_init_prometheus.sql: |
    -- Based on https://clickhouse.com/docs/engines/table-engines/special/time_series
    -- Create database for Prometheus metrics
    CREATE DATABASE IF NOT EXISTS prometheus;
    
    -- Create the TimeSeries table with default schema
    CREATE TABLE IF NOT EXISTS prometheus.metrics
    ENGINE = TimeSeries;
