---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/version: 25.3.6.10034
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: clickhouse-data
      podTemplate: clickhouse-pod
      serviceTemplate: clickhouse-service
  useTemplates:
    - name: clickhouse-data
    - name: clickhouse-pod
    - name: clickhouse-service
  configuration:
    users:
      default/networks/ip: 0.0.0.0/0
      default/access_management: 1
      default/named_collection_control: 1
      default/show_named_collections: 1
      default/show_named_collections_secrets: 1
      default/password:
        valueFrom:
          secretKeyRef:
            name: user-default-credentials
            key: password
    profiles:
      default/allow_experimental_time_series_table: 1
      default/http_connection_timeout: 30
    files:
      prometheus.xml: |
        <clickhouse>
          <prometheus>
            <port>9363</port>
            <handlers>
              <remote_write_rule>
                <url>/write</url>
                <handler>
                  <type>remote_write</type>
                  <database>prometheus</database>
                  <table>metrics</table>
                </handler>
              </remote_write_rule>
            </handlers>
          </prometheus>
        </clickhouse>
    clusters:
      - name: main
        layout:
          shardsCount: 1
          replicasCount: 1
